apiVersion: v1
kind: Service
metadata:
  name: web-http
spec:
  type: ClusterIP
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 3000
      targetPort: "http"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: {{ imageName }}
          resources: {}
          envFrom:
            - configMapRef:
                name: web-config
          ports:
            - name: http
              containerPort: 3000
